- CHANGELOG.md
- inselect/gui/views/boxes/boxes_view.py
- inselect/gui/views/boxes/graphics_item_view.py
> Zoom to box

- CHANGELOG.md
- inselect/gui/main_window.py
> Menu ellipsis

- CHANGELOG.md
- inselect/lib/persist_user_template.py
- inselect/lib/utils.py
> [#193] Better logic when checking for duplicated metadata values

- CHANGELOG.md
- inselect/gui/views/boxes/boxes_view.py
> [#196] refresh view on colour scheme change

- CHANGELOG.md
- inselect/gui/views/boxes/boxes_view.py
> [#48] Zooming follows mouse

- CHANGELOG.md
- inselect/lib/document.py
- inselect/lib/ingest.py
- inselect/scripts/export_metadata.py
- inselect/scripts/ingest.py
- inselect/scripts/read_barcodes.py
- inselect/scripts/save_crops.py
- inselect/tests/lib/test_document.py
> [#230] ingest can set thumbnail pixels

- CHANGELOG.md
- inselect/gui/cookie_cutter_widget.py
- inselect/gui/main_window.py
- inselect/gui/user_template_choice.py
- inselect/gui/user_template_popup_button.py
- inselect/gui/views/metadata.py
- inselect/tests/gui/test_cookie_cutter.py
- inselect/tests/gui/test_metadata_view.py
- inselect/tests/gui/test_user_template_choice.py
> [#234] metadata template popup

- CHANGELOG.md
- inselect/gui/copy_box.py
- inselect/gui/utils.py
- inselect/tests/gui/test_file_open.py
> [#217] first pass at preventing error box from appearing twice

- CHANGELOG.md
- inselect/gui/views/boxes/boxes_view.py
> [#236] Reset zoom when opening new document

- CHANGELOG.md
- inselect/gui/model.py
- inselect/gui/views/object.py
> [#240] Better object labels

- CHANGELOG.md
- inselect/gui/main_window.py
> [#242] Avoid reload of full-res image

- CHANGELOG.md
- inselect/gui/cookie_cutter_widget.py
> [#248] better default text in Cookie Cutter dropdown

- CHANGELOG.md
- inselect/gui/views/metadata.py
> [#249] Better handling of multiple and unrecognised metadata values

- CHANGELOG.md
- inselect/lib/document_export.py
- inselect/lib/image.py
- inselect/lib/persist_user_template.py
- inselect/lib/user_template.py
- inselect/tests/gui/test_export_csv.py
- inselect/tests/lib/test_document_export.py
- inselect/tests/lib/test_persist_user_template.py
- inselect/tests/lib/test_user_template.py
- inselect/tests/scripts/test_export_metadata.py
> [#247] Locations of bounding boxes in CSV

- CHANGELOG.md
- inselect/lib/persist_user_template.py
- inselect/tests/lib/test_persist_user_template.py
> [#254] Better error message when 'Choices with data' is not a mapping

- CHANGELOG.md
- inselect/gui/user_template_choice.py
- inselect/gui/user_template_popup_button.py
> [#256] Disable template 'Reload' command when default template selected

- CHANGELOG.md
- inselect/gui/main_window.py
> [#258] CTRL + number to select view

- CHANGELOG.md
- inselect/scripts/export_metadata.py
- inselect/scripts/ingest.py
- inselect/scripts/read_barcodes.py
- inselect/scripts/save_crops.py
- inselect/scripts/segment.py
> [#262] Scripts respect keyboard interrupt

- CHANGELOG.md
- inselect/gui/plugins/subsegment.py
- inselect/tests/gui/test_subsegment.py
- inselect/tests/test_data/test_subsegment.inselect
> [#263] Subsegment copies metadata to new boxes

- CHANGELOG.md
- inselect/__init__.py
- inselect/gui/plugins/subsegment.py
- inselect/tests/gui/test_subsegment.py
> [#277] Subsegment box broken

- CHANGELOG.md
- inselect/gui/views/boxes/box_item.py
- inselect/gui/views/boxes/resize_handle.py
> [#203] resize handles constant size regardless of zoom

- CHANGELOG.md
- inselect/lib/ingest.py
- inselect/tests/scripts/test_ingest.py
> [#281] Don't make images read-only

- CHANGELOG.md
- inselect/gui/info_widget.py
> [#284] links to show files

- CHANGELOG.md
- inselect/gui/main_window.py
- inselect/gui/views/boxes/boxes_view.py
- inselect/tests/gui/test_boxes_view.py
> [#296] Inconsistent zoom toggling

- CHANGELOG.md
- inselect.py
> [#298] Patch DLL path

- CHANGELOG.md
- inselect/gui/info_widget.py
- inselect/gui/main_window.py
- inselect/gui/plugins/barcode.py
- inselect/tests/gui/test_read_barcodes.py
- inselect/tests/gui/test_save_crops.py
> [#305] Remove references to 'scanned image'

- CHANGELOG.md
- inselect/gui/main_window.py
- inselect/gui/shortcuts_help.py
> [#320] Some view menu items missing from keyboard shortcuts box

- CHANGELOG.md
- inselect/gui/plugins/barcode_dialog.py
> [#330] libdmtx URL incorrect

- CHANGELOG.md
- inselect/lib/utils.py
- inselect/tests/lib/test_utils.py
> [#333] Ugly error message when opening or saving a file

- build.sh
Tidies up a warning from packaging, probably a good idea anyway?
> Build.sh shebang

- CHANGELOG.md
- bin/plist.py
- inselect.py
- inselect/scripts/export_metadata.py
- inselect/scripts/ingest.py
- inselect/scripts/read_barcodes.py
- inselect/scripts/save_crops.py
- inselect/scripts/segment.py
- setup.py
> [#347] python2 in scripts

- CHANGELOG.md
- inselect/lib/utils.py
- inselect/tests/lib/test_utils.py
> [#368] non-latin username

- CHANGELOG.md
- inselect/lib/utils.py
- inselect/tests/lib/test_utils.py
> [#377] Windows non-latin username test

- CHANGELOG.md
- requirements.pip
- setup.py
> [#379] Gouda v0.1.10

- CHANGELOG.md
- inselect/gui/shortcuts_help.py
> [#369] shorter dialog box

- CHANGELOG.md
- requirements.pip
- setup.py
> [#401] New barcode readers

- CHANGELOG.md
- inselect/gui/main_window.py
- inselect/tests/gui/test_active_view.py
> [#406] how Boxes view on creating new document

- CHANGELOG.md
- inselect/lib/fix_frozen.py
- inselect/lib/utils.py
- inselect/scripts/export_metadata.py
- inselect/scripts/ingest.py
- inselect/scripts/inselect.py
- inselect/scripts/read_barcodes.py
- inselect/scripts/save_crops.py
- inselect/scripts/segment.py
> [#414] dll path running frozen on Windows

- CHANGELOG.md
- requirements.pip
- setup.py
> [#418] Latest gouda and pylibdmtx

- CHANGELOG.md
- inselect/gui/main_window.py
- inselect/gui/model.py
- inselect/gui/utils.py
- inselect/tests/gui/test_file_open.py
- inselect/tests/gui/test_utils.py
> [#416] Detect failure to create QImage or QPixel

- CHANGELOG.md
- inselect.spec
> [#420] zbar decoder on Mac OS X

- CHANGELOG.md
- inselect/gui/about.py
> [#309] Homepage link

- CHANGELOG.md
- build.sh
- inselect/lib/document.py
- inselect/lib/parse.py
- inselect/tests/gui/test_export_csv.py
- inselect/tests/gui/test_utils.py
- inselect/tests/lib/test_document.py
- inselect/tests/lib/test_utils.py
- inselect/tests/scripts/test_ingest.py
> [#425] Warnings

- author/trustees-of-the-natural-history-museum-london.html
- category/news.html
- inselect-webinar.html
- pages/documentation.html
- pages/faqs.html
- plos-one-paper-published.html
> resolve references securely
